gluten/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    # ex: /
    path('', views.IndexView.as_view(), name='index'),
    path('menu/', views.Menu, name='menu'),
    # ex: categor/5/
    path('categor/<int:categor_id>/', views.detail, name='detail'),
    # ex: recept/5/
    path('recept/<int:recept_id>/', views.CurRec, name='recept'),
    # ex: addrecept/
    path('addrecept/', views.NewRecView.as_view(), name='add'),
    # ex: delete/5/
    path('delete/<int:recept_id>/', views.DelRec, name='delete'),
    # ex: addcom/5/
    path('addcom/<int:recept_id>/', views.NewComView.as_view(), name='add_com'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('gluten.urls')),
    path('admin/', admin.site.urls),
]

gluten/models.py
from django.db import models
from django.utils.timezone import now
import jsonfield

class Categor(models.Model):
    title = models.CharField(default='Test',max_length=200)

    def __str__(self):
        return self.title

class Recept(models.Model):
    name = models.CharField(default='',max_length=200)
    types = models.ForeignKey(Categor,default=0,on_delete=models.CASCADE)
    comp = jsonfield.JSONField(default='')
    description = models.CharField(default='',max_length=200)
    pub_date = models.DateTimeField(default=now,blank=True)
    likes = models.IntegerField(default=0)
    img = models.ImageField(upload_to ='uploads/', default='none.png')

    def __str__(self):
            return format(self.pub_date.strftime('%d.%m.%Y %H:%M'))
            
    def __str__(self):
        return self.name
        
class Text(models.Model):
    recept = models.ForeignKey(Recept, on_delete=models.CASCADE)
    recept_text = models.CharField(default='',max_length=200)
    img = models.ImageField(upload_to ='uploads/Recepts/', blank=True)

    def __str__(self):
        return self.recept_text


class Comment(models.Model):
    recept = models.ForeignKey(Recept, on_delete=models.CASCADE)
    comment_text = models.CharField(default='Default',max_length=200)
    img = models.ImageField(upload_to ='uploads/Comments/', blank=True)
    pub_date = models.DateTimeField(default=now,blank=True)

    def __str__(self):
        return self.comment_text

gluten/forms.py
from django import forms
from .models import *


class ReceptForm(forms.ModelForm):
    class Meta:
        model = Recept
        fields = ['name', 'types', 'description', 'img']

gluten/views.py
from django.http import HttpResponse, Http404, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.urls import reverse
from django.views.generic import ListView, DetailView
import json
import requests
from django.core import serializers
from django.views import View
from .forms import *


from .models import Recept, Text, Categor


class IndexView(ListView):
    template_name = 'index.html'

    def get_queryset(self):
        """Return the last five published questions."""
        return "Ok"

def Menu(request):
    menu_list = Categor.objects.values('id', 'title')
    return JsonResponse({'data': list(menu_list)})


def detail(request, categor_id):
    try:
        recepts = Recept.objects.filter(types=categor_id)
    except Recept.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'recepts.html', {'recepts': recepts})
def CurRec(request, recept_id):
    try:
        data =[]
        data.append(list(Recept.objects.filter(id=recept_id).values()))
        data.append(list(Text.objects.filter(recept=recept_id).values()))
        data.append(list(Comment.objects.filter(recept=recept_id).values().order_by('-pub_date')))
        
    except Recept.DoesNotExist:
        raise Http404("Recept does not exist")
    return render(request, 'recept.html', {'recept': data})

def add_text(id, data):
    for i in data:
        print(id, i)

class NewRecView(View):    
    def post(self, request):
        print('HERE_rec')
        data=request.POST
        files = request.FILES.getlist('file')

        if request.method == 'POST':
            Name = data['name']
            Types = Categor.objects.get(id=data['types'])
            Description = data['description']
            Components = json.loads(data['text'])
            recept = Recept()
            recept.name = Name
            recept.types = Types
            recept.comp = Components
            recept.description = Description
            if files != []:
                recept.img = files[0]
            recept.save()
            # add_text(recept.id, text)
            return HttpResponse(status=201)

class NewComView(View):    
    def post(self, request, recept_id):
        print('HERE_com')
        data=request.POST
        Text = data['text']
        # files = request.FILES
        # print(files)
        if request.method == 'POST':
            rec = Recept.objects.get(id=recept_id)
            comment = Comment()
            comment.recept = rec
            comment.comment_text = Text
            # if files != []:
                # comment.img = files[0]
            comment.save()
            # return HttpResponse(status=201)
            return redirect('/recept/'+str(recept_id)+'/')
        else:
            return HttpResponse(status=999)

def DelRec(request, recept_id):
    print('HERE_del_rec')
    try:
        rec = Recept.objects.get(id=recept_id)
        rec.delete()
        return HttpResponseRedirect("/")   
    except Recept.DoesNotExist:
        raise Http404("Recept does not exist")
 

templates/Moon/detail.html
<h1>{{ recept.name }} -- {{recept.types}} </h1>
{% for comp in recept.text_set.all %}
    <li>{{ comp.recept_text }}</li>
{% endfor %}
</ul>

templates/Moon/index.html
{% if latest_recept_list %}
    <ul>
    {% for recept in latest_recept_list %}
        <li>
            <a href="/{{ recept.id }}/">
                {{ recept.name }}
                <img src="/media/{{ recept.img }}">
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No gluten are available.</p>
{% endif %}

templates/index.html
{% extends 'base.html' %}
{% block title %}
    Главная
{% endblock %}


{% block content %}
<!-- <h1>
    <div class="shadow"></div>
</h1> -->

<div class="wrapper">
    <!-- <img src="https://sun9-57.userapi.com/c857136/v857136167/14eee5/rxUdD-lqtRA.jpg">
    <img src="https://sun9-24.userapi.com/c205828/v205828167/dbe78/ecKopb7zJbg.jpg">
    <img src="https://sun9-34.userapi.com/c205816/v205816167/cee79/sqwzPtLf7s0.jpg">
    <img src="https://sun9-32.userapi.com/c857024/v857024167/e9151/pnpywGXkc8M.jpg"> -->
    <img src="{{ MEDIA_URL }}/media/main.jpg">
</div><br><br>

<div class="content">
    <p class="text_1">
    <h4 class="sdek">На этой страничке вы увидите только очень вкусные, свежие, а главное безвредные рецепты.
        Целиакией называют врожденное заболевание, связанное с непереносимостью белка некоторых злаковых культур
        (пшеницы, ячменя, ржи), называемых глютеном.
        У больных целиакией глютен вызывает иммунную реакцию в тонком кишечнике. Со временем эта реакция приводит к
        воспалению, которое повреждает эпителий тонкого кишечника и нарушает всасывание некоторых питательных
        веществ (синдром мальабсорбции).
        Повреждение кишечника может привести к потере веса, вздутию живота, а иногда и диарее. В запущенных стадиях
        болезни мозг пациента, нервная система, кости, печень и другие органы - лишаются жизненно важных питательных
        веществ, что и определяет клиническую картину этого заболевания.</h4>
    </p>
    <!-- <p><img class="glut" src="{{ MEDIA_URL }}/media/scale_1200.png"></p> -->
    <!-- <p><img class="glut" src="{{ MEDIA_URL }}/media/krupy.jpg"></p> -->
{% endblock %}

templates/old/Torty_site.html
 <html>
    <head>

        <title>Страничка</title>
        <link rel="stylesheet" href="style.css" type="text/css"/>
        <link href="https://fonts.googleapis.com/css?family=Ruslan+Display&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Russo+One&display=swap" rel="stylesheet">
        <meta charset="utf-8">
        </head>
    
    <body class="div">
        
       
        <nav id="menu1">
            <ul>
                <li><a href="/index.html ">Главная</a></li>
                <li><a>Мои работы</a>
                    <ul>
                        <li><a href="/chizkeiki.html">Чизкейки🍰</a>
                        </li>
                        <li><a href="#">Выпечка🍕</a>
                            <ul>
                                <li><a href="/pirogi_i_pechenki.html">Пироги и печенье🍪</a></li>
                                <li><a href="/Zapekanki.html">Запеканки🥮</a></li>
                                <li><a href="/Torty.html">Торты🎂</a></li>
                                <li><a href="/pizza.html">Пицца🍕</a></li>
                            </ul>
                        </li>
                        <li><a href="/shaurma.html">Шаурма🌯</a></li>
                        <li><a href="/plov.html">Плов🍚+🍖</a></li>
                        <li><a href="/omlet.html">Омлет🍳</a></li>
                    </ul>
                </li>
                <li><a href="/contacts.html">Контакты📱</a>
        </nav>

        <br><br><br><br>

    <center>
<div class="text">Торты🎂
    </center>        
<div class="text">
<center>  
                <img src="https://sun9-22.userapi.com/c858328/v858328167/1c0dc7/-GGHlH5cWPo.jpg" class="amg">
<figcaption>Медовик</figcaption>
<br>
                <img src="https://sun9-44.userapi.com/c857024/v857024167/e9128/TKhqHku4SeY.jpg" class="amg">
<figcaption>Торт медовый</figcaption>
</center>  
</body>
</html>

templates/old/index_site.html
<html>

<head>

    <title>free-glutenchik</title>
    <link rel="stylesheet" href="style.css" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Ruslan+Display&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Russo+One&display=swap" rel="stylesheet">
    <meta charset="utf-8">
</head>

<body class="div">

    
    <nav id="menu1">
        <ul>
            <li><a href="/index.html">Главная</a></li>
            
            <li><a>Мои работы</a>
                <ul>
                    <li><a href="/chizkeiki.html">Чизкейки🍰</a>
                    </li>
                    <li><a href="#">Выпечка🍕</a>
                        <ul>
                            <li><a href="/pirogi_i_pechenki.html">Пироги и печенье🍪</a></li>
                            <li><a href="/Zapekanki.html">Запеканки🥮</a></li>
                            <li><a href="/Torty.html">Торты🎂</a></li>
                            <li><a href="/pizza.html">Пицца🍕</a></li>
                        </ul>
                    </li>
                    <li><a href="/shaurma.html">Шаурма🌯</a></li>
                    <li><a href="/plov.html">Плов🍚+🍖</a></li>
                    <li><a href="/omlet.html">Омлет🍳</a></li>
                </ul>
            </li>
            <li><a href="/contacts.html">Контакты📱</a>
    </nav>

    <br><br><br><br>



    <h1>
        <div class="shadow">Главная
    </h1>
    
    <div class="wrapper">
        <div class="wrap">
            <div class="gradient"><img src="https://sun9-57.userapi.com/c857136/v857136167/14eee5/rxUdD-lqtRA.jpg">
            </div>
        </div>
        <img src="https://sun9-24.userapi.com/c205828/v205828167/dbe78/ecKopb7zJbg.jpg">
        <img src="https://sun9-34.userapi.com/c205816/v205816167/cee79/sqwzPtLf7s0.jpg">
        <img src="https://sun9-32.userapi.com/c857024/v857024167/e9151/pnpywGXkc8M.jpg">
    </div><br><br>

    <div class="content">
        <p class="text_1">
        <h2 class="sdek">На этой страничке вы увидите только очень вкусные, свежие, а главное безвредные рецепты. Вообще
            изначально готовил страничку для себя, а потом подумал, а почему бы не продолжить её развитие.
            Целиакией называют врожденное заболевание, связанное с непереносимостью белка некоторых злаковых культур
            (пшеницы, ячменя, ржи), называемого глютеном.
            У больных целиакией глютен вызывает иммунную реакцию в тонком кишечнике. Со временем эта реакция приводит к
            воспалению, которое повреждает эпителий тонкого кишечника и нарушает всасывание некоторых питательных
            веществ (синдром мальабсорбции).
            Повреждение кишечника может привести к потере веса, вздутию живота, а иногда и диарее. В запущенных стадиях
            болезни мозг пациента, нервная система, кости, печень и другие органы - лишаются жизненно важных питательных
            веществ, что и определяет клиническую картину этого заболевания.</h2>
        </p>
        <p>
            {{ friends|safe }}
            {{ icecreams|safe }}
        </p>
        <p><img class="glut" src="scale_1200.png"></p>
        <p><img class="glut" src="krupy.jpg"></p>



</body>

</html>

templates/recept.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<!-- Главная -->
{% endblock %}


{% block content %}
<div id="recept">
    <button type="button" onclick="location.href = '/delete/{{ recept.0.0.id }}/'" class="btn btn-primary del_recept">
        Удалить рецепт
    </button>
    <div id="recept_block">
        <div class="recept_content">
            <!-- <p>{{ recept.0.0 }}</p> -->
            <p>Название: {{ recept.0.0.name }}</p>
            <p>Описание: {{ recept.0.0.description }}</p>
            <p>Дата публикации: {{recept.0.0.pub_date|time:"H:i"}} {{ recept.0.0.pub_date|date:"d M Y" }}</p>
            <p>Список ингредиентов:</p>
            
            <ul class="">
                {% for item in recept.0.0.comp %}
                <li>{{ item.name }} -- {{ item.size }} -- {{ item.measure }}</li>
                {% endfor %}
            </ul> 
            <!-- <p>Лайки: {{ recept.0.0.likes }}</p> -->
            <svg><use xlink:href="{% static 'like-svgrepo-com.svg' %}"></use></svg>

            

            <p><img src="" ></p>
        </div>
        {% for item in recept.1 %}
            <div class="">
                <p>{{ item.recept_text }}</p>
                {% if item.img %}
                    <p><img src="{{ MEDIA_URL }}/media/{{ item.img }}" class="amg"></p>
                {% endif %}
            </div> 
        {% endfor %}
        <form action="{% url 'add_com' recept.0.0.id %}" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <div class="form-floating">
                    <textarea  name="text" class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px"></textarea>
                    <label style="color: #444;" for="floatingTextarea2">Ваш комментарий</label>
                </div>
                <br>
                <!-- <div class="input-group mb-3">
                    <label class="input-group-text" for="inputGroupFile01">Изображение к комментарию</label>
                    <input name="file" type="file" class="form-control" id="inputGroupFile01">
                </div> -->
                <button type="submit" class="btn btn-outline-primary">Добавить</button>
            </div>
        </form>
        {% for item in recept.2 %}
            <div class="">
                <p class="comments_list">{{ item.comment_text }}</p>
                {% if item.img %}
                    <p><img src="{{ MEDIA_URL }}/media/{{ item.img }}" class="amg"></p>
                {% endif %}
            </div> 
        {% endfor %}
    </div>
</div>
<!-- <div class="text">
    <center>
    </center>  
</div> -->
{% endblock %}

templates/recepts.html
{% extends 'base.html' %}
{% block title %}
<!-- Главная -->
{% endblock %}


{% block content %}
<center>
    <div class="text">{{ recepts.0.types }}</div>
</center>
<div class="text">
    <center>  
        {% for recept in recepts %}
            <div id="rec">
                <a href="/recept/{{ recept.id }}/">
                    <div id="rec_content">
                            <img src="/media/{{ recept.img }}" class="amg">
                            {{ recept.name }}
                            <p id="description">{{ recept.description }}</p>
                        <br>
                    </div>
                </a>
            </div>
        {% endfor %}
</center>  
</div>
{% endblock %}